In [1]:
import VanRoosbrockEg
from mpdbase import *
import numpy as np
% matplotlib inline

# initializing model
model = VanRoosbrockEg.MPD_VanRoosbrockEg(np.linspace(0, 0.5, 10))

# initializing state
state = MPDState(model)


In [2]:
print(model)

----MPD----
--name: VanRoosbrockEg
--parent: http://mathhub.info/MitM/Modelss
---Quantity Decl---
name: electron_mobility
parent: http://mathhub.info/MitM/Modelss?Quantities
dimension: 
---Quantity Decl---
name: doping_profile
parent: http://mathhub.info/MitM/Modelss?Quantities
dimension: VolumeDensity
---Quantity Decl---
name: electron_density
parent: http://mathhub.info/MitM/Modelss?Quantities
dimension: VolumeDensity
---Quantity Decl---
name: charge_density
parent: http://mathhub.info/MitM/Modelss?Quantities
dimension: 
---Quantity Decl---
name: displacement
parent: http://mathhub.info/MitM/Modelss?Quantities
dimension: 
---Quantity Decl---
name: quasifermi_potential
parent: http://mathhub.info/MitM/Modelss?Quantities
dimension: ElectricPotential
---Quantity Decl---
name: electrostatic_potential
parent: http://mathhub.info/MitM/Modelss?Quantities
dimension: ElectricPotential
---Quantity Decl---
name: electric_field
parent: http://mathhub.info/MitM/Modelss?Quantities
dimension: Elect

In [3]:
state.absolute_permittivity

array([[8.85418782e-12],
       [8.85418782e-12],
       [8.85418782e-12],
       [8.85418782e-12],
       [8.85418782e-12],
       [8.85418782e-12],
       [8.85418782e-12],
       [8.85418782e-12],
       [8.85418782e-12],
       [8.85418782e-12]])

In [4]:
state.relative_permittivity.fill(2.0) # set to 2
state.absolute_permittivity = model['permitivity_law'].absolute_permittivity(state) # evaluate law and update
state.absolute_permittivity # print new value

array([[1.77083756e-11],
       [1.77083756e-11],
       [1.77083756e-11],
       [1.77083756e-11],
       [1.77083756e-11],
       [1.77083756e-11],
       [1.77083756e-11],
       [1.77083756e-11],
       [1.77083756e-11],
       [1.77083756e-11]])

In [5]:
state.displacement = numpy.array([[float(x)/10.0, float(x)/10.0, float(x)/10.0] for x in range(-5, 5, 1)])
#print(divergence(state.displacement, model.space))
np.array([np.sum(x) for x in np.sum(np.gradient(state.displacement),axis=0)])

array([0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3])

In [6]:
print(model.computation_steps["cycle1"])

name: cycle1
parent: http://mathhub.info/MitM/Modelss?VanRoosbrockEg?cycle1
steps: gauss_law <- charge_density <~~ charge_density_law <- electron_density <~~ electron_density_law <- electrostatic_potential <~~ electric_field_law <- electric_field <~~ displacement_relation <- displacement


In [7]:
# try computing cycle from current state and print the new state
print(model.computation_steps["cycle1"].compute(state))
print(state.displacement)

[[-0.5 -0.5 -0.5]
 [-0.4 -0.4 -0.4]
 [-0.3 -0.3 -0.3]
 [-0.2 -0.2 -0.2]
 [-0.1 -0.1 -0.1]
 [ 0.   0.   0. ]
 [ 0.1  0.1  0.1]
 [ 0.2  0.2  0.2]
 [ 0.3  0.3  0.3]
 [ 0.4  0.4  0.4]]
[[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
[[-2.14271345e-11 -2.30208883e-11 -2.12500508e-11]
 [-2.14271345e-11 -2.30208883e-11 -2.12500508e-11]
 [-2.14271345e-11 -2.30208883e-11 -2.12500508e-11]
 [-2.14271345e-11 -2.30208883e-11 -2.12500508e-11]
 [-2.14271345e-11 -2.30208883e-11 -2.12500508e-11]
 [-2.14271345e-11 -2.30208883e-11 -2.12500508e-11]
 [-2.14271345e-11 -2.30208883e-11 -2.12500508e-11]
 [-2.14271345e-11 -2.30208883e-

/home/aiman/Git/Physics MPD/physics/source_export/python/VanRoosbrockEg.py:300: RuntimeWarning: invalid value encountered in log
  compute = lambda state: ((state['absolute_permittivity'] * (- gradient(((((numpy.log((((divergence(state['displacement'], self.space) / state['elementary_charge']) - state['doping_profile']) / state['band_density'])) * (state['boltzmann_constant'] * state['temperature'])) + state['band_energy']) / state['elementary_charge']) + state['quasifermi_potential']), self.space)))),


In [8]:
# now do a gauss seidel iteration on the cycle and then print state
state.gauss_seidel("cycle1", epsilon=1e-3)

[[-0.5 -0.5 -0.5]
 [-0.4 -0.4 -0.4]
 [-0.3 -0.3 -0.3]
 [-0.2 -0.2 -0.2]
 [-0.1 -0.1 -0.1]
 [ 0.   0.   0. ]
 [ 0.1  0.1  0.1]
 [ 0.2  0.2  0.2]
 [ 0.3  0.3  0.3]
 [ 0.4  0.4  0.4]]
[[nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]


/home/aiman/Git/Physics MPD/physics/source_export/python/VanRoosbrockEg.py:229: RuntimeWarning: invalid value encountered in log
  electrostatic_potential = lambda state: ((((numpy.log((state['electron_density'] / state['band_density'])) * (state['boltzmann_constant'] * state['temperature'])) + state['band_energy']) / state['elementary_charge']) + state['quasifermi_potential']),


In [9]:
print(state)

electron_mobility
doping_profile
electron_density
charge_density
displacement
quasifermi_potential
electrostatic_potential
electric_field
current_density
absolute_permittivity
relative_permittivity
test_quantity2
test_quantity
band_energy
band_density
temperature
boltzmann_constant
elementary_charge
electric_constant
----MPD State----
electron_mobility: [[0.0001]
 [0.0001]
 [0.0001]
 [0.0001]
 [0.0001]
 [0.0001]
 [0.0001]
 [0.0001]
 [0.0001]
 [0.0001]]
doping_profile: [[1.e-21]
 [1.e-21]
 [1.e-21]
 [1.e-21]
 [1.e-21]
 [1.e-21]
 [1.e-21]
 [1.e-21]
 [1.e-21]
 [1.e-21]]
electron_density: [[-1.31071692e+19 -1.31071692e+19 -1.31071692e+19 -1.31071692e+19
  -1.31071692e+19 -1.31071692e+19 -1.31071692e+19 -1.31071692e+19
  -1.31071692e+19 -1.31071692e+19]
 [-1.31071692e+19 -1.31071692e+19 -1.31071692e+19 -1.31071692e+19
  -1.31071692e+19 -1.31071692e+19 -1.31071692e+19 -1.31071692e+19
  -1.31071692e+19 -1.31071692e+19]
 [-1.31071692e+19 -1.31071692e+19 -1.31071692e+19 -1.31071692e+19
  -1.310